### ISSUE TITLE
Questions of usage

### ISSUE THREAD

**Issue by samveen** [holysnippet/pico_eth_doc#2]
_First, Thank you for your amazing work (I was still dreaming of this, while you had already made it)._

I am trying to figure out what all I need to do such that I can use this as a replacement for ENC28J60 SPI ethernet module family for my Raspberry PI Zero family boards.

Questions on H/W
- For the RJ45 jack with integrated transformer, would the following work:
  - [Ethernet RJ45 Connector Female with Magnetics 10/100 Base-T - LPJ4011ABNL](https://evelta.com/rj45-connector-female-with-magnetics-10-100-base-t-lpj4011abnl/)
  - Given the above Jack, are the passives required the same as listed under the the section [Physical interface, cheap DIY version](https://github.com/holysnippet/pico_eth_doc#physical-interface-cheap-diy-version) , except the T1?
- You mentioned the ISL3177:  Could I try and adapt something from the following schematic - https://github.com/cnlohr/espthernet/blob/gh-pages/hardware/esp12e-ethernet.pdf 
-  What constraints should I be aware of if I want to try and make the total DIY circuit (jack + passives) on a single perfboard that plugs into the headers of the Pico

For the software I plan on doing the following:
- use the offical SPI slave example as a base, and include this library (https://github.com/raspberrypi/pico-examples/tree/master/spi/spi_master_slave/spi_slave)
- Simulate the operations of the ENC28J60 as expected by ENC28J60 drivers, so that the pico_eth registers as an EC28J60. That allows me to use the pico_eth as an in-place replacement, with no additional changes master-side.

Any clarification would be greatly welcome

**Comment by holysnippet** [comment]
Hello, thank you for your interest in this project!

I can't think of any reason why this transformer wouldn't work. It's identical to one of the models I use and doesn't even have the center of the windings interconnected. It's theoretically the ideal model.

Nevertheless, I recommend that you try it out before buying more than one of these transformers. In the "Troubleshooting guide" section it is pointed out that you can omit C3 & C4 in this very specific case, but I strongly advise you to leave them in, as they slightly attenuate the electrical switching noise and prevent, in all situations, any direct current from passing through the transformer winding.

In fact, the diagram you need is identical to the one supplied. I repeat, however, that you should carry out tests beforehand.

There are no particular constraints, but I strongly advise against Breadboards; you won't get the results you're looking for. Perfboards are OK if you work cleanly. Look at the photos; the prototypes are made on Perfboards. The photo in the "Assembly guidelines" section is an example of what you should try to do; keep the connections short so you don't get in trouble.

The software compiles and is ready to use. Pay attention to your version of the Pico SDK. I advise you to use only the latest one (1.5.1 at this time).

For your developments, I refer you to the lwIP documentation. I haven't had the time or the motivation to continue my work on the Ethernet library for the time being. The lwIP threaded API is not available as NO_SYS=1. I haven't had the motivation to write the synchronization layer between the SDK, lwIP and my library. There is no technical limitation to this as far as I know, just code to write. It's even possible to integrate it with FreeRTOS and use the whole thing as you would a Pico-W: it also uses lwIP!

The truth is that in my applications I'm quite happy with the basic API (you can do anything with it, even MQTT in just a few minutes). I thought I'd get some help to continue this project. Personally, I think it's very interesting and I'd love to run it under FreeRTOS, but there's still a lot of work to be done, and the quality of my documentation is mediocre, for example. It's not just code. I'd also need a small bench to test the library; I've got the basic diagnostics but iPerf2 (the only thing available) isn't great.

**Comment by holysnippet** [comment]
About ISL3177 it's a very good idea and a basic scheme should work. The problem is that I haven't continued that part either. I'd need an ISL3177 to test and be able to tell you for sure.
